export const countries: { countryCode: string; countryName: string }[] = [
    { countryCode: 'AED', countryName: 'United Arab Emirates Dirham        ' },
    { countryCode: 'AFN', countryName: 'Afghan Afghani' },
    { countryCode: 'ALL', countryName: 'Albanian Lek' },
    { countryCode: 'AMD', countryName: 'Armenian Dram' },
    { countryCode: 'ANG', countryName: 'Netherlands Antillean Guilder' },
    { countryCode: 'AOA', countryName: 'Angolan Kwanza' },
    { countryCode: 'ARS', countryName: 'Argentine Peso' },
    { countryCode: 'AUD', countryName: 'Australian Dollar' },
    { countryCode: 'AWG', countryName: 'Aruban Florin' },
    { countryCode: 'AZN', countryName: 'Azerbaijani Manat' },
    { countryCode: 'BAM', countryName: 'Bosnia-Herzegovina Convertible Mark' },
    { countryCode: 'BBD', countryName: 'Barbadian Dollar' },
    { countryCode: 'BDT', countryName: 'Bangladeshi Taka' },
    { countryCode: 'BGN', countryName: 'Bulgarian Lev' },
    { countryCode: 'BHD', countryName: 'Bahraini Dinar' },
    { countryCode: 'BIF', countryName: 'Burundian Franc' },
    { countryCode: 'BMD', countryName: 'Bermudan Dollar' },
    { countryCode: 'BND', countryName: 'Brunei Dollar' },
    { countryCode: 'BOB', countryName: 'Bolivian Boliviano' },
    { countryCode: 'BRL', countryName: 'Brazilian Real' },
    { countryCode: 'BSD', countryName: 'Bahamian Dollar' },
    { countryCode: 'BTC', countryName: 'Bitcoin' },
    { countryCode: 'BTN', countryName: 'Bhutanese Ngultrum' },
    { countryCode: 'BWP', countryName: 'Botswanan Pula' },
    { countryCode: 'BYN', countryName: 'New Belarusian Ruble' },
    { countryCode: 'BYR', countryName: 'Belarusian Ruble' },
    { countryCode: 'BZD', countryName: 'Belize Dollar' },
    { countryCode: 'CAD', countryName: 'Canadian Dollar' },
    { countryCode: 'CDF', countryName: 'Congolese Franc' },
    { countryCode: 'CHF', countryName: 'Swiss Franc' },
    { countryCode: 'CLF', countryName: 'Chilean Unit of Account (UF)' },
    { countryCode: 'CLP', countryName: 'Chilean Peso' },
    { countryCode: 'CNY', countryName: 'Chinese Yuan' },
    { countryCode: 'COP', countryName: 'Colombian Peso' },
    { countryCode: 'CRC', countryName: 'Costa Rican Colón' },
    { countryCode: 'CUC', countryName: 'Cuban Convertible Peso' },
    { countryCode: 'CUP', countryName: 'Cuban Peso' },
    { countryCode: 'CVE', countryName: 'Cape Verdean Escudo' },
    { countryCode: 'CZK', countryName: 'Czech Republic Koruna' },
    { countryCode: 'DJF', countryName: 'Djiboutian Franc' },
    { countryCode: 'DKK', countryName: 'Danish Krone' },
    { countryCode: 'DOP', countryName: 'Dominican Peso' },
    { countryCode: 'DZD', countryName: 'Algerian Dinar' },
    { countryCode: 'EGP', countryName: 'Egyptian Pound' },
    { countryCode: 'ERN', countryName: 'Eritrean Nakfa' },
    { countryCode: 'ETB', countryName: 'Ethiopian Birr' },
    { countryCode: 'EUR', countryName: 'Euro' },
    { countryCode: 'FJD', countryName: 'Fijian Dollar' },
    { countryCode: 'FKP', countryName: 'Falkland Islands Pound' },
    { countryCode: 'GBP', countryName: 'British Pound Sterling' },
    { countryCode: 'GEL', countryName: 'Georgian Lari' },
    { countryCode: 'GGP', countryName: 'Guernsey Pound' },
    { countryCode: 'GHS', countryName: 'Ghanaian Cedi' },
    { countryCode: 'GIP', countryName: 'Gibraltar Pound' },
    { countryCode: 'GMD', countryName: 'Gambian Dalasi' },
    { countryCode: 'GNF', countryName: 'Guinean Franc' },
    { countryCode: 'GTQ', countryName: 'Guatemalan Quetzal' },
    { countryCode: 'GYD', countryName: 'Guyanaese Dollar' },
    { countryCode: 'HKD', countryName: 'Hong Kong Dollar' },
    { countryCode: 'HNL', countryName: 'Honduran Lempira' },
    { countryCode: 'HRK', countryName: 'Croatian Kuna' },
    { countryCode: 'HTG', countryName: 'Haitian Gourde' },
    { countryCode: 'HUF', countryName: 'Hungarian Forint' },
    { countryCode: 'IDR', countryName: 'Indonesian Rupiah' },
    { countryCode: 'ILS', countryName: 'Israeli New Sheqel' },
    { countryCode: 'IMP', countryName: 'Manx pound' },
    { countryCode: 'INR', countryName: 'Indian Rupee' },
    { countryCode: 'IQD', countryName: 'Iraqi Dinar' },
    { countryCode: 'IRR', countryName: 'Iranian Rial' },
    { countryCode: 'ISK', countryName: 'Icelandic Króna' },
    { countryCode: 'JEP', countryName: 'Jersey Pound' },
    { countryCode: 'JMD', countryName: 'Jamaican Dollar' },
    { countryCode: 'JOD', countryName: 'Jordanian Dinar' },
    { countryCode: 'JPY', countryName: 'Japanese Yen' },
    { countryCode: 'KES', countryName: 'Kenyan Shilling' },
    { countryCode: 'KGS', countryName: 'Kyrgystani Som' },
    { countryCode: 'KHR', countryName: 'Cambodian Riel' },
    { countryCode: 'KMF', countryName: 'Comorian Franc' },
    { countryCode: 'KPW', countryName: 'North Korean Won' },
    { countryCode: 'KRW', countryName: 'South Korean Won' },
    { countryCode: 'KWD', countryName: 'Kuwaiti Dinar' },
    { countryCode: 'KYD', countryName: 'Cayman Islands Dollar' },
    { countryCode: 'KZT', countryName: 'Kazakhstani Tenge' },
    { countryCode: 'LAK', countryName: 'Laotian Kip' },
    { countryCode: 'LBP', countryName: 'Lebanese Pound' },
    { countryCode: 'LKR', countryName: 'Sri Lankan Rupee' },
    { countryCode: 'LRD', countryName: 'Liberian Dollar' },
    { countryCode: 'LSL', countryName: 'Lesotho Loti' },
    { countryCode: 'LTL', countryName: 'Lithuanian Litas' },
    { countryCode: 'LVL', countryName: 'Latvian Lats' },
    { countryCode: 'LYD', countryName: 'Libyan Dinar' },
    { countryCode: 'MAD', countryName: 'Moroccan Dirham' },
    { countryCode: 'MDL', countryName: 'Moldovan Leu' },
    { countryCode: 'MGA', countryName: 'Malagasy Ariary' },
    { countryCode: 'MKD', countryName: 'Macedonian Denar' },
    { countryCode: 'MMK', countryName: 'Myanma Kyat' },
    { countryCode: 'MNT', countryName: 'Mongolian Tugrik' },
    { countryCode: 'MOP', countryName: 'Macanese Pataca' },
    { countryCode: 'MRO', countryName: 'Mauritanian Ouguiya' },
    { countryCode: 'MUR', countryName: 'Mauritian Rupee' },
    { countryCode: 'MVR', countryName: 'Maldivian Rufiyaa' },
    { countryCode: 'MWK', countryName: 'Malawian Kwacha' },
    { countryCode: 'MXN', countryName: 'Mexican Peso' },
    { countryCode: 'MYR', countryName: 'Malaysian Ringgit' },
    { countryCode: 'MZN', countryName: 'Mozambican Metical' },
    { countryCode: 'NAD', countryName: 'Namibian Dollar' },
    { countryCode: 'NGN', countryName: 'Nigerian Naira' },
    { countryCode: 'NIO', countryName: 'Nicaraguan Córdoba' },
    { countryCode: 'NOK', countryName: 'Norwegian Krone' },
    { countryCode: 'NPR', countryName: 'Nepalese Rupee' },
    { countryCode: 'NZD', countryName: 'New Zealand Dollar' },
    { countryCode: 'OMR', countryName: 'Omani Rial' },
    { countryCode: 'PAB', countryName: 'Panamanian Balboa' },
    { countryCode: 'PEN', countryName: 'Peruvian Nuevo Sol' },
    { countryCode: 'PGK', countryName: 'Papua New Guinean Kina' },
    { countryCode: 'PHP', countryName: 'Philippine Peso' },
    { countryCode: 'PKR', countryName: 'Pakistani Rupee' },
    { countryCode: 'PLN', countryName: 'Polish Zloty' },
    { countryCode: 'PYG', countryName: 'Paraguayan Guarani' },
    { countryCode: 'QAR', countryName: 'Qatari Rial' },
    { countryCode: 'RON', countryName: 'Romanian Leu' },
    { countryCode: 'RSD', countryName: 'Serbian Dinar' },
    { countryCode: 'RUB', countryName: 'Russian Ruble' },
    { countryCode: 'RWF', countryName: 'Rwandan Franc' },
    { countryCode: 'SAR', countryName: 'Saudi Riyal' },
    { countryCode: 'SBD', countryName: 'Solomon Islands Dollar' },
    { countryCode: 'SCR', countryName: 'Seychellois Rupee' },
    { countryCode: 'SDG', countryName: 'Sudanese Pound' },
    { countryCode: 'SEK', countryName: 'Swedish Krona' },
    { countryCode: 'SGD', countryName: 'Singapore Dollar' },
    { countryCode: 'SHP', countryName: 'Saint Helena Pound' },
    { countryCode: 'SLE', countryName: 'Sierra Leonean Leone' },
    { countryCode: 'SLL', countryName: 'Sierra Leonean Leone' },
    { countryCode: 'SOS', countryName: 'Somali Shilling' },
    { countryCode: 'SRD', countryName: 'Surinamese Dollar' },
    { countryCode: 'SSP', countryName: 'South Sudanese Pound' },
    { countryCode: 'STD', countryName: 'São Tomé and Príncipe Dobra' },
    { countryCode: 'SVC', countryName: 'Salvadoran Colón' },
    { countryCode: 'SYP', countryName: 'Syrian Pound' },
    { countryCode: 'SZL', countryName: 'Swazi Lilangeni' },
    { countryCode: 'THB', countryName: 'Thai Baht' },
    { countryCode: 'TJS', countryName: 'Tajikistani Somoni' },
    { countryCode: 'TMT', countryName: 'Turkmenistani Manat' },
    { countryCode: 'TND', countryName: 'Tunisian Dinar' },
    { countryCode: 'TOP', countryName: 'Tongan Paʻanga' },
    { countryCode: 'TRY', countryName: 'Turkish Lira' },
    { countryCode: 'TTD', countryName: 'Trinidad and Tobago Dollar' },
    { countryCode: 'TWD', countryName: 'New Taiwan Dollar' },
    { countryCode: 'TZS', countryName: 'Tanzanian Shilling' },
    { countryCode: 'UAH', countryName: 'Ukrainian Hryvnia' },
    { countryCode: 'UGX', countryName: 'Ugandan Shilling' },
    { countryCode: 'USD', countryName: 'United States Dollar' },
    { countryCode: 'UYU', countryName: 'Uruguayan Peso' },
    { countryCode: 'UZS', countryName: 'Uzbekistan Som' },
    { countryCode: 'VEF', countryName: 'Venezuelan Bolívar Fuerte' },
    { countryCode: 'VES', countryName: 'Sovereign Bolivar' },
    { countryCode: 'VND', countryName: 'Vietnamese Dong' },
    { countryCode: 'VUV', countryName: 'Vanuatu Vatu' },
    { countryCode: 'WST', countryName: 'Samoan Tala' },
    { countryCode: 'XAF', countryName: 'CFA Franc BEAC' },
    { countryCode: 'XAG', countryName: 'Silver (troy ounce)' },
    { countryCode: 'XAU', countryName: 'Gold (troy ounce)' },
    { countryCode: 'XCD', countryName: 'East Caribbean Dollar' },
    { countryCode: 'XDR', countryName: 'Special Drawing Rights' },
    { countryCode: 'XOF', countryName: 'CFA Franc BCEAO' },
    { countryCode: 'XPF', countryName: 'CFP Franc' },
    { countryCode: 'YER', countryName: 'Yemeni Rial' },
    { countryCode: 'ZAR', countryName: 'South African Rand' },
    { countryCode: 'ZMK', countryName: 'Zambian Kwacha (pre-2013)' },
    { countryCode: 'ZMW', countryName: 'Zambian Kwacha' },
    { countryCode: 'ZWL', countryName: 'Zimbabwean Dollar' }]